// src/livecodes/languages/solid/jsx-runtime.ts
export const solidRuntime = `
import { render, createComponent } from "solid-js/web";
import App from "./script";
(() => {
  const isSolidComponent = (c) => typeof c === "function" && /return\\s+\\(?\\s*function\\s+\\(\\)\\s+{/g.test(String(c));
  if (!isSolidComponent(App)) return;
  const root = document.querySelector("#livecodes-app") || document.body.appendChild(document.createElement("div"));
  render(() => createComponent(App, {}), root);
})();
`;

// src/livecodes/languages/react-native/jsx-runtime.ts
export const reactNativeRuntime = `
import { AppRegistry } from "react-native";
import App from "./script";
(() => {
  const isReactComponent = (c) => typeof c === "function" && (/(return|=>)\\s+\\(?\\s*(_jsx|React\\.createElement)/g.test(String(c)) || Boolean(c.prototype?.isReactComponent));
  if (!isReactComponent(App)) return;
  const rootTag = document.querySelector("#livecodes-app") || document.body.appendChild(document.createElement("div"));
  AppRegistry.registerComponent("App", () => App);
  AppRegistry.runApplication("App", { rootTag });
})();
`;
