// src/livecodes/languages/jsx/react-runtime.ts
export const reactRuntime = `
import { jsx as _jsx } from "react/jsx-runtime";
import { createRoot } from "react-dom/client";
import App from "./script";
(() => {
  if (typeof App !== "function") return;
  const root = createRoot(document.querySelector("#livecodes-app") || document.body.appendChild(document.createElement("div")));
  root.render(_jsx(App, {}));
})();
`;

// src/livecodes/languages/solid/solid-runtime.ts
export const solidRuntime = `
import { render, createComponent } from "solid-js/web";
import App from "./script";
(() => {
  if (typeof App !== "function") return;
  const root = document.querySelector("#livecodes-app") || document.body.appendChild(document.createElement("div"));
  render(() => createComponent(App, {}), root);
})();
`;
