// src/localpen/templates/starter/solid-starter.ts
import { Template } from '../../models';

export const solidStarter: Template = {
  name: 'solid',
  title: 'Solid Starter',
  thumbnail: 'assets/templates/solid.svg',
  activeEditor: 'script',
  markup: {
    language: 'html',
    content: '<div id="app"></div>\n',
  },
  style: {
    language: 'css',
    content: `
.container,
.container button {
  text-align: center;
  font: 1em sans-serif;
}
.logo {
  width: 150px;
}
`.trimStart(),
  },
  script: {
    language: 'solid.tsx',
    content: `
import { render } from "solid-js/web";
import { createSignal } from "solid-js";

type Props = {
  title: string;
}

function App(props: Props) {
  const [count, setCount] = createSignal(0);
  const increment = () => setCount(count() + 1);

  return (
    <div className="container">
      <h1>Hello, {props.title}!</h1>
      <img className="logo" src="{{ __localpen_baseUrl__ }}assets/templates/solid.svg" />
      <p>You clicked {count} times.</p>
      <button onClick={increment}>Click me</button>
    </div>
  );
}

render(() => <App title="Solid" />, document.getElementById("app"));
`.trimStart(),
  },
  stylesheets: [],
  scripts: [],
  cssPreset: '',
  imports: {},
  types: {
    'solid-js': `{{ __localpen_baseUrl__ }}types/solid-js.d.ts`,
  },
};

// src/localpen/templates/starter/react-starter.ts
import { Template } from '../../models';

export const reactStarter: Template = {
  name: 'react',
  title: 'React Starter',
  thumbnail: 'assets/templates/react.svg',
  activeEditor: 'script',
  markup: {
    language: 'html',
    content: '<div id="app">Loading...</div>\n',
  },
  style: {
    language: 'css',
    content: `
.container,
.container button {
  text-align: center;
  font: 1em sans-serif;
}
.logo {
  width: 150px;
}
`.trimStart(),
  },
  script: {
    language: 'jsx',
    content: `
import React, { useState } from "react";
import ReactDOM from "react-dom";

function App(props) {
  const [count, setCount] = useState(0);

  return (
    <div class="container">
      <h1>Hello, {props.name}!</h1>
      <img src="{{ __localpen_baseUrl__ }}assets/templates/react.svg" className="logo" />
      <p>You clicked {count} times.</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}
ReactDOM.render(<App name="React" />, document.querySelector("#app"));
`.trimStart(),
  },
  stylesheets: [],
  scripts: [],
  cssPreset: '',
  imports: {},
  types: {},
};
