// src/localpen/templates/starter/solid-starter.ts
import { Template } from '../../models';

export const solidStarter: Template = {
  name: 'solid',
  title: 'Solid Starter',
  thumbnail: 'assets/templates/solid.svg',
  activeEditor: 'script',
  markup: {
    language: 'html',
    content: '<div id="app"></div>\n',
  },
  style: {
    language: 'css',
    content: `
.container,
.container button {
  text-align: center;
  font: 1em sans-serif;
}
.logo {
  width: 150px;
}
`.trimStart(),
  },
  script: {
    language: 'solid.tsx',
    content: `
import { render } from "solid-js/web";
import { createSignal } from "solid-js";

type Props = {
  title: string;
}

function App(props: Props) {
  const [count, setCount] = createSignal(0);
  const increment = () => setCount(count() + 1);

  return (
    <div className="container">
      <h1>Hello, {props.title}!</h1>
      <img className="logo" src="{{ __localpen_baseUrl__ }}assets/templates/solid.svg" />
      <p>You clicked {count} times.</p>
      <button onClick={increment}>Click me</button>
    </div>
  );
}

render(() => <App title="Solid" />, document.getElementById("app"));
`.trimStart(),
  },
  stylesheets: [],
  scripts: [],
  cssPreset: '',
  imports: {},
  types: {
    'solid-js': `{{ __localpen_baseUrl__ }}types/solid-js.d.ts`,
  },
};

// src/localpen/templates/starter/stencil-starter.ts
import { Template } from '../../models';

export const stencilStarter: Template = {
  name: 'stencil',
  title: 'Stencil Starter',
  thumbnail: 'assets/templates/stencil.png',
  activeEditor: 'script',
  markup: {
    language: 'html',
    content: '<my-app title="Stencil"></my-app>\n',
  },
  style: {
    language: 'css',
    content: '',
  },
  script: {
    language: 'stencil',
    content: `
import { Component, Prop, h, State } from "@stencil/core";

@Component({
  tag: "my-app",
  styles: \`
    my-app,
    button {
      text-align: center;
      font: 1em sans-serif;
    }
    .logo {
      width: 150px;
    }
  \`,
})
export class App {
  @Prop() title: string;
  @State() count = 0;

  increment = () => {
    this.count += 1;
  };

  render() {
    return (
      <div class="container">
        <h1>Hello, {this.title}!</h1>
        <img src="{{ __localpen_baseUrl__ }}assets/templates/stencil.png" class="logo" />
        <p>You clicked {this.count} times</p>
        <button onClick={this.increment}>Click me</button>
      </div>
    );
  }
}
`.trimStart(),
  },
  stylesheets: [],
  scripts: [],
  cssPreset: '',
  imports: {},
  types: {},
};
