// web/src/components/LiveCodes.tsx
import React, { useEffect, useRef } from 'react';
// eslint-disable-next-line import/no-unresolved
import { appUrl } from '../utils';
// eslint-disable-next-line import/no-internal-modules
import { playground, Config } from '../../../src/lib/livecodes';
import ShowCode from './ShowCode';
import styles from './LiveCodes.module.css';

const url = appUrl + '?';

export default function LiveCodes(props: {
  config?: Config;
  template?: string;
  query?: string;
  style?: Record<string, string>;
  showCode?: boolean;
}): JSX.Element {
  const containerRef = useRef(null);
  useEffect(() => {
    playground(containerRef.current, {
      appUrl: url + props.query,
      template: props.template,
      config: props.config,
    });
  }, []);

  const options = {
    ...(props.query ? { appUrl: url + props.query } : {}),
    ...(props.template ? { template: props.template } : {}),
    ...(props.config ? { config: props.config } : {}),
  };

  const code = `
import { playground } from '@live-codes/livecodes';

const options = ${JSON.stringify(options, null, 2)};
playground('#container', options);

`.trimStart();

  return (
    <>
      <div ref={containerRef} className={styles.container} style={props.style}></div>
      {props.showCode !== false && <ShowCode language="js">{code}</ShowCode>}
    </>
  );
}

// docs/src/components/LiveCodes.tsx
import React from 'react';
/* eslint-disable import/no-internal-modules */
import type { EmbedOptions } from '../../../src/sdk';
import LiveCodesReact from '../../../src/sdk/react';
import { appUrl } from '../utils';
import ShowCode from './ShowCode';
import styles from './LiveCodes.module.css';

export default function LiveCodes(
  props: EmbedOptions & {
    style?: Record<string, string>;
    className?: string;
    showCode?: boolean;
  },
): JSX.Element {
  const { className, style, showCode, ...options } = props;

  const jsCode = `
import { createPlayground } from 'livecodes';

const options = ${JSON.stringify(options, null, 2)};
createPlayground('#container', options);

`.trimStart();

  const tsCode = `
import { createPlayground, type EmbedOptions } from 'livecodes';

const options: EmbedOptions = ${JSON.stringify(options, null, 2)};
createPlayground('#container', options);

`.trimStart();

  const reactCode = `
import LiveCodes from 'livecodes/react';

export default function App() {
  const options = ${JSON.stringify(options, null, 2)};
  return (<LiveCodes {...options}></LiveCodes>);
}

`.trimStart();

  const vueCode = `
<script setup>
import LiveCodes from "livecodes/vue";

const options = ${JSON.stringify(options, null, 2)};
</script>
<template>
  <LiveCodes v-bind="options" />
</template>

`;

  const svelteCode = `
<script>
import { onMount } from 'svelte';
import { createPlayground } from 'livecodes';

const options = ${JSON.stringify(options, null, 2)};
let container;
onMount(() => {
  createPlayground(container, options);
});
</script>

<div bind:this="{container}"></div>

`.trimStart();

  return (
    <>
      <LiveCodesReact
        className={`${styles.container} ${props.className}`}
        style={{
          height: '50vh',
          ...props.style,
        }}
        appUrl={appUrl}
        {...props}
      ></LiveCodesReact>
      {props.showCode !== false && (
        <ShowCode
          js={jsCode}
          ts={tsCode}
          react={reactCode}
          vue={vueCode}
          svelte={svelteCode}
        ></ShowCode>
      )}
    </>
  );
}
